name: Inspur Request Transformer
dbless_compatible: yes
dbless_explanation: It is recommended to use in dbless mode.
publisher: Inspur

categories:
  - transformations

type: plugin

desc: Kong plugin to transform diversiform requests
description: |

  Transform the request sent by a client on the fly on Kong, before hitting the upstream server.

  The plugin implements parameter transformations and additions of various positions.

support_url: https://github.com/cheriL/apig-request-transformer/issues

source_code: https://github.com/cheriL/apig-request-transformer

license_type: Apache-2.0

kong_version_compatibility:
  community_edition:
    compatible:
      - 1.2.x
      - 1.1.x
